export const LOGIN_USER="LOGIN_USER"; 
export const LOGOUT_USER="LOGOUT_USER"; 

export const GET_USERS_LIST="GET_USERS_LIST"; 
export const GET_SINGLE_USER="GET_SINGLE_USER"; 

export const NAVIGATE_MAIN_PAGE="NAVIGATE_MAIN_PAGE"; 
export const NAVIGATE_USER_PAGE="NAVIGATE_USER_PAGE"; 